#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors =  true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#asciidoc"

[[layers]]
name = 'lang#python'

[[layers]]
name = "lang#javascript"

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true

[[layers]]
name = "lang#typescript"

[[layers]]
    name = 'git'

[[layers]]
    name = 'VersionControl'

 [[layers]]
  name = "debug"
  debugger_plugin = "vimspector"

[[layers]]
  name = "lang#assembly"

[[layers]]
  name = "lang#autohotkey"

[[layers]]
  name = "lang#batch"

[[layers]]
    name = 'lsp'
    enabled_clients = ['vimls', 'clangd', 'intelephense', 'jdtls']

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#r"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#plantuml"
  plantuml_jar_path = "/usr/share/plantuml/plantuml.jar"


 [[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#json"


    [[layers]]
  name = 'lang#java'
  format_on_save = true

  [[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#dart"

    [[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "ui"

