name: Continous Integration

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    name: 🚀 Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11.0
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: true

      - name: Install
        run: echo "$HOME/.dotfiles" | bash installer

      - name: Debug on error
        if: ${{ failure() }}
        run: |
          echo "DOTFILES_REPOSITORY: $DOTFILES_REPOSITORY"
          echo "DOTFILES_BRANCH: $DOTFILES_BRANCH"
          echo "DOTFILES_ENV: $DOTFILES_ENV"
          cat "$HOME/dotfiles.log"